name: Morales Bot - Feature to Develop

on:
  push:
    branches:
      - feature/*

permissions:
  contents: write
  packages: write
  issues: write
  pull-requests: write

jobs:
  android:
    uses: pgsilva/deck-actions/.github/workflows/gh-create-pr-feat.yml@v2
    with:
      branch: develop